### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by AntonioAsr** [aholachek/react-animation-comparison#3]
Hello, 

I have tried to run this project but couldn't get it to work. I also refactor some code but didn't success to make it work.
None of the npm commands in the package.json works for me... I runned npm install.
Are these examples supposed to be executable or they are only there as code examples?
Any guidelines on how to get it up and running would be great!

Thank you very much!

**Comment by aholachek** [comment]
Hi Antonio,

Thanks for pointing out this issue, I should have documented it. To run the examples you have to run storybook, I've added [instructions at the bottom of the readme here](https://github.com/aholachek/react-animation-comparison#run-the-project-locally)

Please let me know if this doesn't work for you.

**Comment by AntonioAsr** [comment]
Hi aholacheck,

It works for me now :) Thanks for the early answer and the code examples. Great work!!

Antonio
