### ISSUE TITLE
react-pose has been updated and pretty bug free

### ISSUE THREAD

**Issue by bushblade** [aholachek/react-animation-comparison#4]
Hi, really interesting repo, I just stumbled on it as i've been doing something similar myself here
[my animation library testing](https://github.com/bushblade/react-animations-test)

I found some bugs in react-pose too and reported them, the developers responded very swiftly with a fixed version release.
I also managed to use the library to animate svg paths [codeSandbox here](https://codesandbox.io/s/github/bushblade/svg-testing/tree/master/?module=%2Fsrc%2FLogo.js)

**Comment by aholachek** [comment]
That svg path animation is beautiful! 
I just updated to V4 of pose but unfortunately I could still reproduce the 2 issues I wrote about in the readme. [Here's the issue I made back in May for the most problematic bug, it looks like it won't be super straightforward to fix](https://github.com/Popmotion/popmotion/issues/320)
