### ISSUE TITLE
Successor to react-pose, framer-motion

### ISSUE THREAD

**Issue by WilsonCWong** [aholachek/react-animation-comparison#7]
Hey,

The successor to Pose by Popmotion, Framer Motion, was open-sourced today: https://github.com/framer/motion

Could be good for trying out when you next update the comparison.

**Comment by mrmckeb** [comment]
Yes it would be great to see this added. They apparently resolved many of the issues in Pose.

**Comment by aholachek** [comment]
Done! It definitely seems to be working better than Pose, it looks great.
